Change displayed currency
Pearson-Advance/openedx-themes pull request #159
Opened 2021-08-04 18:55 UTC by Jacatove

# Description:

This PR is intended to make the benefit price of a coupon consistent with the currency of the purchase. The following screenshot illustrates the issue, there are both `$` and `£`.

Ticket: [PAE-777](https://pearsonadvance.atlassian.net/browse/PAE-777)

![$](https://user-images.githubusercontent.com/40271196/128237985-aa17424f-988f-42ac-8dc9-69feaaee5c4f.png)

# Changes done:

![$](https://user-images.githubusercontent.com/40271196/128237271-03e61522-0c23-491c-983c-19ae637bea55.png)

The changes do not affect the percentage discount.
![%](https://user-images.githubusercontent.com/40271196/128237284-7ae894ee-79d0-4cdf-9b3d-dee0335a9e9d.png)

2021-08-04 23:04 UTC, ivanvgh approved these changes
LGTM!

2021-08-05 00:17 UTC, Squirrel18 commented on ecommerce/pols/templates/oscar/basket/partials/hosted_checkout_basket.html
> +                                        {% if "$" in line_data.benefit_value %}
Could you add a comment related to what you're doing here? @Jacatove Add it as a template comment, not an HTML comment.

2021-08-10 03:32 UTC, Squirrel18 requested changes

2021-08-10 03:32 UTC, Squirrel18 commented on ecommerce/pols/templates/oscar/basket/partials/hosted_checkout_basket.html
> +                                            purchase currency, |currency:line_data.line.price_currency.
```suggestion
                                            The line_data.benefit_value could be either a percentage or a currency
                                            value (50.0% $50.0), This is an issue if the currency of the purchase is
                                            different than "$". The idea here is to get rid of the "$" symbol by applying the filter
                                            |cut:"$" and then use the currency filter to format the value with the corresponding
                                            purchase currency, |currency:line_data.line.price_currency.
```

2021-08-10 04:07 UTC, Squirrel18 approved these changes

2021-08-10 04:17 UTC, merged