PAE- 103: Add the dropdown for orgs but as a custom theme
Pearson-Advance/openedx-themes pull request #181
Opened 2021-09-29 19:57 UTC by elvinquero

This PR has to do with https://github.com/Pearson-Advance/edx-platform/pull/53. That PR alter the default index.html from the studio app, which may be not desirable.

With this PR we added the custom index.html. It checks were the new variable, org_names_list exists to create the dropdown, if not, renders the text input, as the default code does.

To activate this theming we will have to:
1. Enable comprehensive theming for Studio.
2. Enable the ORGANIZATION_APP https://github.com/Pearson-Advance/edx-platform/blob/3792f3d740d76b245f7ff05492ede2ce9a637129/cms/envs/common.py#L283 
3. Add the studio URL to the Site Theme table.

2021-09-30 13:04 UTC, Jacatove requested changes
Great! This way We do not touch the studio app. I have a question, isn't worth it to also add this changes to the other theme within eComm which is **pols**?. @elvinquero

2021-09-30 13:04 UTC, Jacatove commented on edx-platform/pearson-pathways-theme/cms/templates/index.html
> +                  </select>
```suggestion
                </select>
```

2021-10-06 02:55 UTC, Squirrel18 requested changes

2021-10-06 02:55 UTC, Squirrel18 commented on edx-platform/pearson-studio-theme/cms/templates/index.html
> +                    <option value="" selected>${_("All organizations")} </option>
nit: Remove the blank space before the closing tag. @anfbermudezme

2021-10-06 02:55 UTC, Squirrel18 commented on edx-platform/pearson-studio-theme/cms/templates/index.html
> +                  </select>
Bad indentation. @anfbermudezme

2021-10-06 16:10 UTC, elvinquero commented
@Squirrel18 suggestions were applied.

2021-10-06 16:49 UTC, anfbermudezme approved these changes

2021-10-06 17:39 UTC, diegomillan approved these changes
LGTM

2021-10-06 18:35 UTC, Jacatove requested changes
@elvinquero Could you please squash the commits. I mean just to have the 2 "feat:..." commits.

2021-10-06 18:50 UTC, Jacatove approved these changes

2021-10-06 19:10 UTC, Squirrel18 approved these changes

2021-10-06 22:58 UTC, Squirrel18 approved these changes

2021-10-07 13:09 UTC, merged