PAE-103 - Enhacement - The dropdown remains selected.
Pearson-Advance/openedx-themes pull request #183
Opened 2021-10-13 22:11 UTC by elvinquero

The [PR for the dropdown](https://github.com/Pearson-Advance/openedx-themes/pull/181), did not left the selected option selected after submit. This PR allows for this behavior to remain.

Reference: [PAE-103](https://pearsonadvance.atlassian.net/browse/PAE-103)

2021-10-13 23:33 UTC, anfbermudezme approved these changes

2021-10-14 15:00 UTC, Jacatove requested changes

2021-10-14 15:00 UTC, Jacatove commented on edx-platform/pearson-studio-theme/cms/templates/index.html
> +                  %endif
What do you think about using an inline if and adding a "All" message?. @elvinquero
```suggestion
                  <option value="" {%if request.GET.get("org") %} selected {%endif%}>All</option>
```

2021-10-14 15:05 UTC, elvinquero commented on edx-platform/pearson-studio-theme/cms/templates/index.html
> +                  %endif
Oh, I knew how to do inline in DjangoTemplate engine but I tried to do it in Mako and failed. I did not know I could use it like this, just like the DjangoTemplate syntax. @Jacatove

2021-10-15 12:11 UTC, Jacatove approved these changes

2021-10-15 15:26 UTC, anfbermudezme approved these changes

2021-10-15 15:34 UTC, merged