PAE-797 - Update any reference to price and discount for special coupons.
Pearson-Advance/openedx-themes pull request #184
Opened 2021-10-21 13:43 UTC by Jacatove

It is important to understand what a _**special coupon**_ is before reading the description of this PR. A _**special coupon**_ is a discount coupon for which the following pages have to suppress any reference to price and discount.
- Enrollment code page
- Order summary
- Receipt

### How to know if we are dealing with a special coupon?.
When creating the coupons it is important to use a prefix for the coupon name, This coupon name `£1|3-special_coupon` will be used in the templates to identify that we are dealing with special coupons. Also, more information is passed to allow custom messages as `Install payment 1/3`, `Install payment 2/5`.

#### special coupon format [4 char]:
{character}{# coupon}|{#  coupons for this purchase}{name of the coupon}
example: `£1|3-special_coupon`

![image](https://user-images.githubusercontent.com/40271196/139276816-69b3ea72-7923-4829-b19c-ef6d729ae0b3.png)

The prefix should be placed in custom_settings (Found in eCommerce site configuration) as `{REMOVE_SPECIAL_COUPON_OFFER_PREFIX:"£"}`

### Description:

This PR has to update the pages mentioned above in order to alter the current visual behavior of coupons.

### Requirements:

This PR  needs an ecommerce update which is found in this complementary PR https://github.com/Pearson-Advance/ecommerce/pull/23
### Result:
The images down below show the progress, there are still pending requirements about what to show when we deal with **_special coupons_**.

**Receipt - Normal Coupon:**
![image](https://user-images.githubusercontent.com/40271196/139447190-a2de43da-b379-48fb-a028-671161deb90a.png)

**Receipt - Special Coupon:**
![image](https://user-images.githubusercontent.com/40271196/139449196-d473fa26-eaf1-4c16-8478-af2aba73b057.png)

**Order Summary - Normal Coupon:**
![image](https://user-images.githubusercontent.com/40271196/139444776-51e432f5-f424-4913-9717-9e69b9717db9.png)

**Order Summary - Special Coupon:**
![image](https://user-images.githubusercontent.com/40271196/139444323-259649a6-9649-454c-91ec-8547aae58580.png)

**Enrollment Code Page - Normal Coupon:**
![image](https://user-images.githubusercontent.com/40271196/138481086-83052cb3-ffa5-41a8-a445-6d4c141c8711.png)

**Enrollment Code Page - Special Coupon:**
![image](https://user-images.githubusercontent.com/40271196/138480929-8c16ec7c-0861-4edd-968c-9b58ce70da9f.png)

2021-10-25 23:52 UTC, elvinquero commented on ecommerce/pathways/templates/oscar/basket/partials/hosted_checkout_basket.html
> +                                {% if custom_settings.INSTALLMENT_PAYMENT_CODE in basket.vouchers.all.0.name %}
Is there a reason why the statement was not negated in favor of just using one if instead of a if-else?

2021-10-25 23:52 UTC, elvinquero commented on ecommerce/pathways/templates/oscar/basket/partials/hosted_checkout_basket.html
> +                                        <form action="{% url 'basket:vouchers-remove' pk=voucher.id %}" method="POST">
form tag is indented as if it were a part of the if statement.

2021-10-25 23:52 UTC, elvinquero commented on ecommerce/pathways/templates/oscar/basket/partials/hosted_checkout_basket.html
> +            </div>
I believe this is intended to be a span to close the previous tag.

2021-10-25 23:56 UTC, elvinquero commented on ecommerce/pathways/templates/oscar/basket/partials/hosted_checkout_basket.html
> +                                {% if custom_settings.INSTALLMENT_PAYMENT_CODE in basket.vouchers.all.0.name %}
I see this happens in another part of the code. Is it for code readability?

2021-10-26 03:59 UTC, Jacatove commented on ecommerce/pathways/templates/oscar/basket/partials/hosted_checkout_basket.html
> +                                {% if custom_settings.INSTALLMENT_PAYMENT_CODE in basket.vouchers.all.0.name %}
The reason might be that I probably will add something for that case, but since it is not specified yet, I will do your suggestion. @elvinquero

2021-10-26 18:16 UTC, elvinquero commented on ecommerce/pathways/templates/edx/checkout/receipt.html
> +              {% if custom_settings.INSTALLMENT_PAYMENT_CODE in discount.voucher.name %}
The if-else could be changed for an if here, too.

2021-11-02 15:38 UTC, elvinquero approved these changes

2021-11-05 22:18 UTC, Squirrel18 requested changes

2021-11-05 22:18 UTC, Squirrel18 commented on ecommerce/pathways/templates/edx/checkout/receipt.html
> +                      Installment payment {{order.basket_discounts.0.voucher.name.1}}/{{order.basket_discounts.0.voucher.name.3}}
Is there a way to avoid index 0 in 'order.basket_discounts.0.voucher.name'? @Jacatove

2021-11-05 22:18 UTC, Squirrel18 commented on ecommerce/pathways/templates/edx/checkout/receipt.html
> +                    </p>
Wrong indentation. @Jacatove

2021-11-05 22:18 UTC, Squirrel18 commented on ecommerce/pathways/templates/oscar/basket/partials/hosted_checkout_basket.html
> +                                <p class="product-description">{{ basket|get_special_coupon_data }}</p>
Wrong indentation. @Jacatove

2021-11-05 22:24 UTC, Jacatove commented on ecommerce/pathways/templates/edx/checkout/receipt.html
> +                      Installment payment {{order.basket_discounts.0.voucher.name.1}}/{{order.basket_discounts.0.voucher.name.3}}
@Squirrel18 This was already addressed using the filter `|get_special_coupon_data`.

2021-11-05 22:46 UTC, Squirrel18 approved these changes

2021-11-10 10:54 UTC, merged