PAE-777.2 - Change displayed currency for Pathways.
Pearson-Advance/openedx-themes pull request #185
Opened 2021-10-25 14:22 UTC by Jacatove

## Description:
This PR applies the same change as in [PAE-777 - Change displayed currency](https://github.com/Pearson-Advance/openedx-themes/pull/159) but to the Pathways Theme. So, this PR fixes the inconsistency of having two different currency symbols `$` and `£`. You can see the issue in the following picture:

![image](https://user-images.githubusercontent.com/40271196/138712222-3b18de6a-2032-4076-9d80-41c544c80a2d.png)

Ticket: [PAE-777](https://pearsonadvance.atlassian.net/browse/PAE-777)

## Changes done:
![image](https://user-images.githubusercontent.com/40271196/138713449-82680f4e-df05-4c09-a320-9bcf2ff593ff.png)

The changes do not affect the percentage discount.

![image](https://user-images.githubusercontent.com/40271196/138704619-c5ac77a4-f280-4c52-a746-adb7d7692adf.png)

2021-10-29 13:28 UTC, anfbermudezme approved these changes

2021-11-26 16:15 UTC, Squirrel18 requested changes

2021-11-26 16:15 UTC, Squirrel18 commented on ecommerce/pathways/templates/oscar/basket/partials/hosted_checkout_basket.html
> +                                        {% endblocktrans %}
Bad indentation. @Jacatove

2021-11-26 19:37 UTC, Squirrel18 approved these changes

2021-11-29 13:21 UTC, merged