PAE-156 - Add the Regis theme.
Pearson-Advance/openedx-themes pull request #210
Opened 2022-06-28 18:29 UTC by Squirrel18

## Description:

This PR adds the base theme for the Regis site.

## Screenshots:

![image](https://user-images.githubusercontent.com/17520199/176222888-6306ac38-7a0c-4bbe-9f43-9902839d1505.png)
![image](https://user-images.githubusercontent.com/17520199/176223937-35b493a3-4135-47f0-adbd-7d2f9d368a68.png)
![image](https://user-images.githubusercontent.com/17520199/176225789-31da0e1e-6438-4db1-8c39-6c2ee7f2b031.png)

## Note:

- This theme is based on the Pathways theme.
- Footer is expected to be changed.

## Testing:

- Check out to this branch.
- Enable Comprehensive theming: https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/changing_appearance/theming/enable_themes.html
- Compile assets, `paver update_assets --themes=pearson-regis-theme`
- Assign 'pearson-regis-theme' to a new site.

## Reviewers:

- [ ] @Jacatove 
- [x] @alexjmpb 
- [ ] @anfbermudezme

2022-06-29 00:13 UTC, alexjmpb requested changes

2022-06-29 00:13 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_buttons.scss
> +input[type="submit"], input[type="button"], button, .button {
```suggestion
input[type="submit"],
input[type="button"],
button,
.button {
```
Would't it be better to break the lines to separate each individual selector?

2022-06-29 21:06 UTC, alexjmpb requested changes

2022-06-29 21:06 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +
```suggestion
.view-dashboard div.item .items.course.single-course {
  float: left;
  margin: 1%;
  min-width: 250px;
  padding: 0;
  width: 23%;

  @include media-breakpoint-down(lg) {
    width: 31%;
  }

  @include media-breakpoint-down(md) {
    width: 49%;
  }

  @include media-breakpoint-down(sm) { 
    width: 98%;
  }
}
```

Would you consider to nest the media queries inside the selector to avoid repetition? And also use Bootstrap's breakpoints instead of the magic methods

2022-06-29 21:06 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +}
```suggestion
.view-dashboard div.item .course .details {

  .enter-course {
    width: 100%;
  }

  .course-actions .wrapper-action-more .btn  {
    color: #007FA3;
    background: #fff;
    float: right;
    font-size: 16px;
    line-height: 24px;
    box-sizing: border-box;
    letter-spacing: 0;
    border: 1px solid #007FA3;
    border-radius: 3px;
    padding: 8px 20px;
    text-align: center;
    width: 100%;
  }
  
  @include media-breakpoint-down(lg) {
    padding-left: 0 !important;
  }
}
```

Same suggestion about Bootstrap breakpoints and nesting

2022-06-29 21:06 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +  }
```suggestion
  @include media-breakpoint-down(md) {
    .course .details .wrapper-course-image {
      display: none;
    }
  }

  @include media-breakpoint-down(md) {
    .course .details .wrapper-course-details {
      display: flex;
      flex-direction: column;
    }
  }

  @include media-breakpoint-down(md) {
    .course .details .wrapper-course-details .course-info,
    .course .details .wrapper-course-details .wrapper-course-actions {
      flex-grow: 1;
      text-align: left;
    }
  }

  @include media-breakpoint-down(md) {
    .course .details .wrapper-course-details
    div.wrapper-course-actions div.course-actions {
      padding-top: 50px;
    }
  }

  @include media-breakpoint-down(md) {
    .course .details .wrapper-course-details .course-info .wrapper-action-more,
    .course .details .wrapper-course-details .course-info .entitlement-actions-wrapper,
    .course .details .wrapper-course-details .wrapper-course-actions .wrapper-action-more,
    .course .details .wrapper-course-details .wrapper-course-actions .entitlement-actions-wrapper {
      padding-top: 3px;
    }
  }
```
Same suggestion about Bootstrap brakpoints

2022-06-29 21:06 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +  padding: 0px;
```suggestion
  padding: 0;
```

I would suggest to remove the px unit to maintain consistency

2022-06-29 21:06 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +    padding-left: 0px !important;
```suggestion
    padding-left: 0 !important;
```

Same suggestion about px unit

2022-06-29 21:06 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +  right: 0px;
```suggestion
  right: 0;
```

Same suggestion about px unit

2022-06-29 21:06 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +    padding: 0px 0px 10px 0px;
```suggestion
    padding: 0 0 10px 0;
```

Same suggestion about px unit

2022-06-29 21:06 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +      margin: 0px !important;
```suggestion
      margin: 0 !important;
```

Same suggestion about px unit

2022-06-29 21:06 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +      padding: 0px;
```suggestion
      padding: 0; 
```

Same suggestion about px unit

2022-06-29 21:06 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +  }
Add line separation

2022-06-29 21:06 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +}
Would you consider to nest these breakpoints to their corresponding selectors from above? Or instead move those breakpoints to here

2022-07-05 04:19 UTC, Squirrel18 commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +  }
I assume you mean indentation... @alexjmpb

2022-07-05 21:50 UTC, alexjmpb approved these changes

2022-07-06 04:03 UTC, anfbermudezme commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_footer.scss
> +        line-height: 26px;
Add blank line.

2022-07-06 14:57 UTC, alexjmpb requested changes

2022-07-06 14:57 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +@include media-breakpoint-down(sm) {
Indent inside same selector of line 185.

2022-07-06 14:57 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +  @include media-breakpoint-down(md) {
Move these properties from line 168 to 180 inside same selector of line 143

2022-07-06 18:37 UTC, anfbermudezme approved these changes

2022-07-06 22:02 UTC, alexjmpb requested changes

2022-07-06 22:02 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
> +    @media (max-width: 767px) {
Apply Boostrap's media queries

2022-07-06 22:12 UTC, alexjmpb approved these changes

2022-07-06 22:21 UTC, merged