PPAE-157 - Styling the header of the Regis theme.
Pearson-Advance/openedx-themes pull request #212
Opened 2022-07-15 07:21 UTC by Squirrel18

## Description:

This PR changes the Regis theme header to comply with the Regis mockups.

## Screenshots:

![image](https://user-images.githubusercontent.com/17520199/179172390-f9f25ac1-d238-48c0-922c-def4e20f40e4.png)
![image](https://user-images.githubusercontent.com/17520199/179172437-caa40060-841a-445f-b6d2-816c8a7fe0f6.png)
![image](https://user-images.githubusercontent.com/17520199/179172489-2e00e488-0a06-4ead-8633-b40671090bbd.png)

## Testing:

- Check out this branch.
- Enable Comprehensive theming: https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/changing_appearance/theming/enable_themes.html
- Compile assets, `paver update_assets --themes=pearson-regis-theme`
- Assign 'pearson-regis-theme' to a new site.

## Reviewers:

- [ ] @alexjmpb 
- [ ] @anfbermudezme

2022-07-16 04:32 UTC, alexjmpb requested changes
All comments are suggestions to improve fidelity to FIgma doc. Would you consider to apply them?

When applied the result should be the following:
![Screenshot 2022-07-15 at 23-29-10 Dashboard Your Platform Name Here](https://user-images.githubusercontent.com/62396424/179339406-b3036025-6c30-4a1e-be7d-be2cdce93110.png)
![Screenshot 2022-07-15 at 23-29-55 Dashboard Your Platform Name Here](https://user-images.githubusercontent.com/62396424/179339410-c511934a-ba76-47aa-b07b-c6427ffbcf06.png)
![Screenshot 2022-07-15 at 23-30-15 Signed Out Your Platform Name Here](https://user-images.githubusercontent.com/62396424/179339413-44370214-4a53-4928-bf41-52b871cbb75f.png)

2022-07-16 04:32 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_navigation.scss
> +    border-bottom: 1px solid $gray;
```suggestion
    border-bottom: 1px solid #D4D7D9;
    box-shadow: none;
    min-height: 100px;
    padding: 0 55px;

    .main-header {
      display: flex;
      align-items: center;
      gap: 60px;
      height: 100px;

      @include media-breakpoint-down(lg) {
        height: 100px;
        justify-content: space-between;
        
        h1 {
          a {
            margin: 0;
          }
        }
      }
    }

```

2022-07-16 04:32 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_navigation.scss
>        .main {
```suggestion
      .main {
        display: flex;
        gap: 30px;
        margin: 0;
        height: 100%;

```

2022-07-16 04:32 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_navigation.scss
>      .nav-links {
```suggestion
    .nav-links {
      display: none;
      align-items: center;
      height: 100%;
      width: 100%;
      justify-content: space-between;

```

2022-07-16 04:32 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_navigation.scss
> +            color: $gray;
```suggestion
            color: $gray;
            display: flex;
            align-items: center;
            height: 100%;
            padding: 0;
            font-weight: 500;
            border-bottom: 5px solid transparent;

```

2022-07-16 04:32 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_navigation.scss
>                font-weight: 700;
```suggestion
              border-bottom-color: $primary-light;
```

2022-07-16 04:32 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_navigation.scss
>        .secondary {
```suggestion
      .secondary {
        display: flex;
        align-items: center;
        margin: 0;
        gap: 30px;

        .nav-item {
          margin: 0;
          
          a {
            font-weight: 500;
          }
        }
```

2022-07-16 04:32 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_navigation.scss
> +          border: none;
```suggestion
          border: none;
          height: 30px;
```

2022-07-16 04:32 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_navigation.scss
> +      @include media-breakpoint-up(lg) {
```suggestion
      @include media-breakpoint-up(lg) {
        display: flex;
```

2022-07-16 04:32 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_navigation.scss
> +      a {
```suggestion
    .header-logo {
      margin: 0;

      a {
        margin: 0;

        .logo {
          height: 30px;
          margin: 0;
        }

```

2022-07-16 04:32 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_navigation.scss
> +        @include right($baseline);
```suggestion
        @include right($baseline);
        position: relative;
        top: 0;
        left: 0;
        padding: 0;
```

2022-07-16 04:32 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_navigation.scss
>  #top {
```suggestion
#top {
  @include media-breakpoint-down(lg) {
    padding: 0 15px !important;
  }

```

2022-07-16 04:32 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_variables.scss
```suggestion
$primary-light: #EE3F40;

```

2022-07-18 14:53 UTC, Squirrel18 commented
Really great suggestions, good work, thanks @alexjmpb

2022-07-18 16:24 UTC, alexjmpb requested changes

2022-07-18 16:24 UTC, alexjmpb commented on edx-platform/pearson-regis-theme/lms/static/sass/partials/lms/theme/_variables.scss
Would you consider add this variable and use it for the color border on line 59 of _navigation.scss

2022-07-18 16:26 UTC, alexjmpb commented
> Really great suggestions, good work, thanks @alexjmpb

Thanks, no worries!!

2022-07-18 21:07 UTC, alexjmpb approved these changes

2022-07-19 01:30 UTC, merged