Pearson/pae 164.2
Pearson-Advance/openedx-themes pull request #220
Opened 2022-08-09 00:32 UTC by alexjmpb

## Description:

This PR fixes feedback comments for the regis ecommerce theme

## Screenshots:

![Screenshot 2022-08-08 at 19-26-39 Receipt for EDX-100011](https://user-images.githubusercontent.com/62396424/183537075-baca35fc-bb6c-4688-a149-1762bf9456cd.png)

![Screenshot 2022-08-08 at 19-32-26 Cart](https://user-images.githubusercontent.com/62396424/183537436-a0915052-d271-4c6a-beb2-dbba0856f8f7.png)

## Reviewers:

- [ ] @alexjmpb 
- [ ] @kuipumu

2022-08-09 17:03 UTC, kuipumu approved these changes

2022-08-10 21:33 UTC, Squirrel18 requested changes

2022-08-10 21:33 UTC, Squirrel18 commented on ecommerce/regis/static/sass/base/_variables.scss
> +$primary-color-dark: #991f34;
Use uppercase to define colour variables. @alexjmpb

2022-08-10 21:33 UTC, Squirrel18 commented on ecommerce/regis/static/sass/base/_variables.scss
> +$font-family-primary: 'Roboto', 'Open Sans';
```suggestion
$font-family-primary: 'Roboto', 'Open Sans', sans;
```

2022-08-10 21:33 UTC, Squirrel18 commented on ecommerce/regis/static/sass/base/_variables.scss
> +}
Missing end of file line. @alexjmpb

2022-08-11 17:03 UTC, Squirrel18 approved these changes

2022-08-11 17:48 UTC, merged