PADV-566: Add default Theme
Pearson-Advance/openedx-themes pull request #247
Opened 2023-06-16 00:36 UTC by sergivalero20

## Ticket

https://agile-jira.pearson.com/browse/PADV-566

## Description

This PR adds assets for default theme on edx-platform.

## Testing:

- Enable comprehensive theming.
- Run the LMS: `make dev.up.lms`.
- Set `pearson-theme` on a site.
- Compile the dafault theme.
- Verify that the default theme is applied correctly on Olive.

(For more information enter here: [How to enable themes)](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/changing_appearance/theming/enable_themes.html#enable-themes)

## Screenshots

Log In:
![image](https://github.com/Pearson-Advance/openedx-themes/assets/73655023/eb20ee71-74f7-4a8a-9a7d-3047c5ebfb68)

Dashboard:
![image](https://github.com/Pearson-Advance/openedx-themes/assets/73655023/5de8c14f-b1b9-4fc7-8db7-5f86af92671a)

## Reviewers

- [ ] @Squirrel18 
- [ ] @alexjmpb

2023-06-16 16:59 UTC, Squirrel18 requested changes

2023-06-16 16:59 UTC, Squirrel18 commented on edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_variables.scss
> +$dark-gray: #767676;
Are all these definitions being used? @sergivalero20

2023-06-16 17:10 UTC, sergivalero20 commented on edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_variables.scss
> +$dark-gray: #767676;
@Squirrel18 changes applied.

2023-06-16 20:45 UTC, alexjmpb approved these changes

2023-06-19 19:56 UTC, Squirrel18 approved these changes

2023-06-19 20:00 UTC, merged